### ISSUE TITLE
Java 8 Support

### ISSUE THREAD

**Issue by Alffrredo** [weblith/weblith#1]
Hello Guys.

Maven repository is based on Java11+ and should be compiled everything for Java8 users

Thanks,

**Comment by jlannoy** [comment]
Hello.
Nope, sorry. Weblith.io is mainly dedicated to offering a base for new projects, which don't have any external requirements, like an application server. So it makes no sense to support Java 8. Furthermore, it's based on Quarkus, which also have [deprecated the support of Java 8 in the 1.4.1 version](https://quarkus.io/blog/quarkus-1-4-final-released/).
